# Nombre del Workflow
name: Run Migrations on Main Merge

# Define cuándo se ejecuta el workflow
on:
  push:
    branches:
      - main  # Se ejecuta solo en pushes (incluyendo merges) a la rama 'main'

# Define los trabajos (jobs) que se ejecutarán
jobs:
  migrate:
    # Nombre del trabajo
    name: Run Database Migrations
    # El tipo de runner donde se ejecutará el trabajo
    runs-on: ubuntu-latest # Puedes usar otras imágenes si necesitas (e.g., windows-latest, macos-latest)

    # Pasos que se ejecutarán secuencialmente
    steps:
      # 1. Checkout del código del repositorio
      - name: Checkout code
        uses: actions/checkout@v4 # Acción oficial para clonar el repositorio

      # 2. Configurar el entorno Python
      - name: Set up Python
        uses: actions/setup-python@v5 # Acción oficial para configurar Python
        with:
          python-version: '3.11' # Especifica la versión de Python que necesitas. Ajústala si usas otra.

      # 3. Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Instala las dependencias desde requirements.txt

      # 4. Ejecutar el script de migración
      # Asegúrate de que tu script tenga acceso a las variables de entorno necesarias (p.ej., conexión a la BD)
      # Usa GitHub Secrets para información sensible.
      - name: Run migrations
        # Añade aquí las variables de entorno que tu script necesite, usando secrets si es necesario
        env:
          SUPABASE_PATH: ${{ secrets.SUPABASE_PATH }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_PW: ${{ secrets.SUPABASE_PW }}
        run: python migrations/migrate_data.py # Ejecuta tu script de migración